name: Action Tilo

on:
  push:
    branches:
      - main
      - master
  workflow_dispatch:

jobs:
  my_action:
    runs-on: ubuntu-latest
    steps:
      - name: Print Hello World
        run: echo "Hello World!"