name: Action Tilo

on:
  workflow_dispatch:

jobs:
  my_action:
    runs-on: ubuntu-latest
    steps:
      - name: Print Hello World
        run: echo "Hello World!"
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu' # See 'Supported distributions' for available options
          java-version: '17'
      - run: java --version

  my_action_2:
    runs-on: ubuntu-latest
    steps:
      - name: Print Hello World
        run: echo "Hello World!"
      - name: Print Hello World
        run: echo "Hello World!"
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu' # See 'Supported distributions' for available options
          java-version: '18'
      - name: Check version
        run: java --version
      - name: Compile code
        run: mvn clean install

  my_action_3:
    runs-on: ubuntu-latest
    needs: [my_action, my_action_2]
    steps:
      - name: Print Hello World
        run: echo "Hello World!"