name: Action Tilo

on:
  workflow_dispatch:

jobs:
  test_chrome:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    env:
      WEBSITE: ${{ secrets.PAGE_URL }}
    services:
      chrome:
        image: selenium/standalone-chrome
        ports:
          - 4444:4444
    steps:
      - name: Print Hello World
        run: echo "Hello World!"
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu' # See 'Supported distributions' for available options
          java-version: '17'
      - run: java --version
      - name: Compile code
        run: mvn clean compile -DskipTests=True --no-transfer-progress
      - name: Print website
        run: echo ${{ env.WEBSITE }}
      - name: Run test cases on Chrome browser
        run: mvn clean test -Ddriver.name=chrome-remote -Ddriver.remoteUrl=http://localhost:4444/wd/hub  --no-transfer-progress
      - name: Archive code coverage results
        uses: actions/upload-artifact@v3
        with:
          name: chrome-reports
          path: logs

  test_firefox:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    services:
      firefox:
        image: selenium/standalone-firefox
        ports:
          - 4445:4444
    steps:
      - name: Print Hello World
        run: echo "Hello World!"
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu' # See 'Supported distributions' for available options
          java-version: '17'
      - run: java --version
      - name: Compile code
        run: mvn clean compile -DskipTests=True --no-transfer-progress
      - name: Run test cases on Firefox browser
        run: mvn clean test -Ddriver.name=firefox-remote -Ddriver.remoteUrl=http://localhost:4445/wd/hub -Dwebsite=https://www.qytera.de --no-transfer-progress
      - name: Archive code coverage results
        uses: actions/upload-artifact@v3
        with:
          name: firefox-reports
          path: logs
