name: Action Tilo

on:
  workflow_dispatch:

jobs:
  test_chrome:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    services:
      chrome:
        image: selenium/standalone-chrome
        ports:
          - 4444:4444
    steps:
      - name: Print Hello World
        run: echo "Hello World!"
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu' # See 'Supported distributions' for available options
          java-version: '17'
      - run: java --version
      - name: Compile code
        run: mvn clean compile -DskipTests=True --no-transfer-progress
      - name: Run test cases on Chrome browser
        run: mvn clean test -Ddriver.name=chrome-remote -Ddriver.remoteUrl=http://localhost:4444/wd/hub  --no-transfer-progress

  test_firefox:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    services:
      firefox:
        image: selenium/standalone-firefox
        ports:
          - 4445:4444
    steps:
      - name: Print Hello World
        run: echo "Hello World!"
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu' # See 'Supported distributions' for available options
          java-version: '17'
      - run: java --version
      - name: Compile code
        run: mvn clean compile -DskipTests=True --no-transfer-progress
      - name: Run test cases on Firefox browser
        run: mvn clean test -Ddriver.name=firefox-remote -Ddriver.remoteUrl=http://localhost:4445/wd/hub  --no-transfer-progress

  my_action_3:
    runs-on: ubuntu-latest
    needs: [my_action, my_action_2]
    steps:
      - name: Print Hello World
        run: echo "Hello World!"