name: Install Java

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  install_java:
    runs-on: windows-latest

    steps:
      - name: Install Java
        uses: actions/setup-java@v2
        with:
          java-version: '17'