name: Install Java

on:
  workflow_dispatch:

jobs:
  install_java:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v3
      - name: Install Java
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'zulu'
      - name: Echo Java version
        run: |
          java --version
      - name: copy git code
        run: |
          ls
      - name: maven clean
        run: mvn clean compile