name: Learn Github Actions

on:
  workflow_dispatch:

jobs:
  install_java:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v3
      - name: Install Java
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'zulu'
      - name: Echo Java version
        run: |
          java --version
      - name: copy git code
        run: |
          ls
      - name: maven clean
        run: mvn clean compile


  build_and_run_on_java_17:
    runs-on: ubuntu-latest
    services:
      chrome:
        image: selenium/standalone-chrome
        ports:
          - 4444:4444
      firefox:
        image: selenium/standalone-firefox
        ports:
          - 4445:4444
    steps:
      - uses: actions/checkout@v3
      - name: Install Java
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'zulu'
      - name: Run tests chrome
        run: mvn clean test -Ddriver.name=chrome-remote -Ddriver.remoteUrl=http://localhost:4444/wd/hub --no-transfer-progress
      - name: Run tests firefox
        run: mvn clean test -Ddriver.name=firefox-remote -Ddriver.remoteUrl=http://localhost:4445/wd/hub --no-transfer-progress

  build_and_run_on_java_17_chrome:
    runs-on: ubuntu-latest
    services:
      chrome:
        image: selenium/standalone-chrome
        ports:
          - 4444:4444
    steps:
      - uses: actions/checkout@v3
      - name: Install Java
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'zulu'
      - name: Run tests chrome
        run: mvn clean test -Ddriver.name=chrome-remote -Ddriver.remoteUrl=http://localhost:4444/wd/hub --no-transfer-progress


  build_and_run_on_java_17_firefox:
    runs-on: ubuntu-latest
    services:
      firefox:
        image: selenium/standalone-firefox
        ports:
          - 4445:4444
    steps:
      - uses: actions/checkout@v3
      - name: Install Java
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'zulu'
      - name: Run tests firefox
        run: mvn clean test -Ddriver.name=firefox-remote -Ddriver.remoteUrl=http://localhost:4445/wd/hub --no-transfer-progress