# Moritz Test Pipeline
name: Moritz Test Pipeline

on:
  workflow_dispatch:

jobs:
   test_execution:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    
    steps:
      - name: Checkout sources
        uses: actions/checkout@v3
      - name: test checkout sources
        run: ls
      - name: Set up JDK 19
        uses: actions/setup-java@v3
        with:
          java-version: '19'
          distribution: 'zulu'
      - name: Test Java installation
        run: java --version
      - name: Complie with Maven (no dependency check)
        run: mvn clean compile -q -B
      - name: Compile with Maven (with dependencies)
        run: mvn clean compile -U   
      - name: Build with Maven (with dependencies)
        run: mvn clean install -q -DskipTests    
        
