name: Action Sebastian

on:
  workflow_dispatch:
    # triggered manually

env:
  JAVA_VERSION: '17'
  JAVA_DISTRIBUTION: 'zulu'
  JAVA_BUILD_TOOL: 'maven'

jobs:
  compile:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        driver: [ 'firefox-remote', 'chrome-remote' ]

    services:
      chrome:
        image: selenium/standalone-chrome
        ports:
          - 4444:4444
      firefox:
        image: selenium/standalone-firefox
        ports:
          - 4445:4444

    steps:
      - uses: actions/checkout@v3
      - name: check directory content
        run: |
          ls -l
      - uses: actions/setup-java@v3
        with:
          java-version: ${{ env.JAVA_VERSION }}
          distribution: ${{ env.JAVA_DISTRIBUTION }}
          cache: ${{ env.JAVA_BUILD_TOOL }}
      - name: check java version
        run: |
          java --version
      - name: run firefox tests
        if: matrix.driver == 'firefox-remote'
        run: |
          mvn test --no-transfer-progress \
          -Ddriver.name=${{ matrix.driver }} \
          -Ddriver.remoteUrl=http://localhost:4445/wd/hub
      - name: run chrome tests
        if: matrix.driver == 'chrome-remote'
        run: |
          mvn test --no-transfer-progress \
          -Ddriver.name=${{ matrix.driver }} \
          -Ddriver.remoteUrl=http://localhost:4444/wd/hub
