name: Action Sebastian

on:
  workflow_dispatch:
    # triggered manually

env:
  JAVA_VERSION: '17'
  JAVA_DISTRIBUTION: 'zulu'
  JAVA_BUILD_TOOL: 'maven'

jobs:
  compile:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-java@v3
        with:
          java-version: ${{ env.JAVA_VERSION }}
          distribution: ${{ env.JAVA_DISTRIBUTION }}
          cache: ${{ env.JAVA_BUILD_TOOL }}
      - name: check java version
        run: |
          java --version
      - uses: actions/checkout@v3
      - name: check directory content
        run: |
          ls -l
      - name: compile code
        run: |
          mvn --version
          mvn compile --no-transfer-progress
