name: Action Sebastian
on:
  release:
    types: [ 'published' ]
  workflow_dispatch:
    # triggered manually

env:
  SOURCE_BRANCH: master
  TEAM_NAME: qytera-admins

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Create pull request
        run: |
          gh pr create \
          -B ${{ github.event.repository.default_branch }} \
          -H ${{ env.SOURCE_BRANCH }} \
          --title 'Release version ${{ github.event.release.name }}' \
          --body 'Created by GitHub action for pushing changes to branch `${{ env.TARGET_BRANCH }}`.'
          --assignee ${{ github.event.release.author.name }}
        env:
          GH_TOKEN: ${{ github.token }}
      #- name: Create Pull Request
      #  uses: peter-evans/create-pull-request@v5
      #  with:
      #    author: GitHub <noreply@github.com>
      #    assignees: ${{ github.event.release.author.name }}
