name: StarterTest

env:
  JAVA_VERSION: '17'
  JAVA_DISTRIBUTION: 'zulu'

on:
  workflow_dispatch:
    # triggered manually

jobs:
  test_huy:
    runs-on: ubuntu-latest
    steps:
      - name: Print helo weorld
        run: echo "Helo, weorld!"
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          java-version: ${{env.JAVA_VERSION}}
          distribution: ${{env.JAVA_DISTRIBUTION}}
          cache: 'maven'
      - name: java --version
        run: java --version
      - name: mvn --version
        run: mvn --version
      - name: check content directory
        run: |
          ls -l
      - name: mvn clean install
        run: mvn clean install -DskipTests


