name: StarterTest

on:
  push:
    branches:
      - main
      - master
  workflow_dispatch:

env:
  JAVA_VERSION: '17'
  JAVA_DISTRIBUTION: 'zulu'

jobs:
  test_huy:
    runs-on: ubuntu-latest
    steps:
      - name: Print helo weorld
        run: echo "Helo, weorld!"
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          java-version: ${{ env.JAVA_VERSION }}
          distribution: 'zulu'
          cache: 'maven'
      - name: java --version
        run: java --version
      - name: mvn --version
        run: mvn --version
      - name: check content directory
        run: |
          ls -l
      - name: mvn clean install
        run: mvn clean install -DskipTests


