name: Action Huy

env:
  JAVA_VERSION: '17'
  JAVA_DISTRIBUTION: 'zulu'
  WEBSITE: 'https://www.google.com'

on:
  workflow_dispatch:
  # triggered manually

jobs:
  test_huy:
    runs-on: ubuntu-latest

    services:
      chrome:
        image: selenium/standalone-chrome
        ports:
          - 4444:4444
      firefox:
        image: selenium/standalone-firefox
        ports:
          - 4445:4444
    strategy:
      matrix:
        browser: [ chrome, firefox ]
        include:
          - browser: chrome
            ports: 4444
          - browser: firefox
            ports: 4445
    steps:
      - name: Print helo weorld
        run: echo "Helo, weorld!"
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          java-version: ${{env.JAVA_VERSION}}
          distribution: ${{env.JAVA_DISTRIBUTION}}
          cache: 'maven'
      - name: java --version
        run: java --version
      - name: mvn --version
        run: mvn --version
      - name: check content directory
        run: |
          ls -l
      - name: mvn clean install
        run: mvn clean install -DskipTests --no-transfer-progress
      - name: Run test ${{matrix.browser}}
        run: mvn clean test -Ddriver.name=${{matrix.browser}}-remote -Ddriver.remoteUrl=http://localhost:${{matrix.ports}}/wd/hub
      - name: check env WEBSITE
        run: echo ${{env.WEBSITE}}
      - name: make logs
        uses: actions/upload-artifact@v2
        with:
          name: artifact-logs
          path: testdir
